# Generated by Django 3.1.7 on 2022-01-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211229_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_scanning',
            field=models.BooleanField(blank=True, default=False, help_text='Se vero significa che si stanno analizzando le foto.<br>Si stanno cercando i volti e generando gli encodings.', null=True, verbose_name='Scannerizzando'),
        ),
    ]
